variables:
  acrName: acrbxpv7s3vsxwh6.azurecr.io
  imageName: 'model-api'

trigger:
  - main

  pool:
    vmImage: 'ubuntu-latest' 

  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(acrName)/$(imageName)
      tags: |
        latest
        $(Build.BuildNumber) 
      command: build
      Dockerfile: Dockerfile