variables:
  acrName: acrbxpv7s3vsxwh6.azurecr.io
  imageName: 'model-api'
  acrConnectionName: acrConnection

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' 

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: buildAndPush
    repository: $(acrName)/$(imageName)
    tags: |
      latest
      $(Build.BuildNumber) 
    dockerfile: Dockerfile
    containerRegistry: $(acrConnectionName)